alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias goJob='cd /mnt/d/_PIK_Projects/'
alias goJob2='cd /mnt/wsl/PHYSICALDRIVE0p1/Pik/'
alias helloSsh='eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa'
alias gitw='git.exe'
